# GitHub Pages configuration for coBoarding documentation menu
# This enables navigation menu on GitHub Pages

# Set theme (minimal is simple and works well with navigation)
# theme: just-the-docs
remote_theme: just-the-docs/just-the-docs
mermaid: true
favicon: "/docs/favicon.svg"

just_the_docs:
  includes:
    head: "docs/_includes/head_custom.html"

# Navigation menu for documentation (visible on GitHub Pages)
# To add more docs, add them to the 'nav' list
nav:
  - Home: README.md
  - Quick Start: README.md#szybki-start
  - Containers: README.md#struktura-kontenerów
  - Tests: README.md#scenariusze-testowe
  - Troubleshooting: README.md#faq
  - Contact: README.md#kontakt-i-wsparcie
