# GitHub Pages configuration for coBoarding documentation menu
# This enables navigation menu on GitHub Pages

# Set theme (minimal is simple and works well with navigation)
# theme: just-the-docs
remote_theme: just-the-docs/just-the-docs
mermaid: true
favicon: "/docs/favicon.svg"

just_the_docs:
  includes:
    head: "_includes/head_custom.html"

# Navigation menu for documentation (visible on GitHub Pages)
# To add more docs, add them to the 'nav' list
nav:
  - title: "Dokumentacja użytkownika"
    children:
      - title: "Start"
        url: "/docs/user/"
      - title: "Szybki start"
        url: "/docs/quickstart.md"
      - title: "Instalacja"
        url: "/docs/install.md"
      - title: "FAQ"
        url: "/docs/faq.md"
      - title: "Przykłady użycia"
        url: "/docs/examples.md"
      - title: "Kontakt"
        url: "/docs/contact.md"
  - title: "Dokumentacja developerska"
    children:
      - title: "Start"
        url: "/docs/dev/"
      - title: "Architektura"
        url: "/docs/architecture.md"
      - title: "Struktura kontenerów"
        url: "/docs/containers.md"
      - title: "Testy end-to-end"
        url: "/docs/e2e-tests.md"
      - title: "FAQ dla developerów"
        url: "/docs/faq.md"
      - title: "Przykłady użycia"
        url: "/docs/examples.md"
      - title: "Changelog"
        url: "/CHANGELOG.md"
      - title: "Porównanie rozwiązań"
        url: "/COMPARE.md"
      - title: "Kontakt"
        url: "/docs/contact.md"
