version: '3.8'
services:
  web-terminal:
    build:
      context: ./containers/web-terminal
    ports:
      - "8081:8081"
    volumes:
      - ~/.cache/pip:/root/.cache/pip
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/"]
      interval: 10s
      timeout: 5s
      retries: 3
