version: '3.8'
services:
  novnc:
    build:
      context: ./containers/novnc
    ports:
      - "6080:6080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6080/"]
      interval: 10s
      timeout: 5s
      retries: 3
