version: '3.8'

services:
  llm-orchestrator:
    build:
      context: ./containers/llm-orchestrator
    container_name: llm-orchestrator
    volumes:
      - ./volumes/models:/app/models
      - ./volumes/config:/app/config
      - ./volumes/cv:/app/cv:ro
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "5000:5000"  # API LLM
    networks:
      - autoformfiller-network

networks:
  autoformfiller-network:
    driver: bridge
