version: '3.8'

services:
  llm-orchestrator:
    build:
      context: ./containers/llm-orchestrator
    container_name: llm-orchestrator
    volumes:
      - ./volumes/models:/app/models
      - ./volumes/config:/app/config
      - ./volumes/cv:/app/cv:ro
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "5000:5000"  # API LLM
    networks:
      - autoformfiller-network

  # Dodaj prosty serwis testowy do przykładowych zapytań
  test-client:
    image: python:3.9-slim
    container_name: test-client
    volumes:
      - ./test-examples:/test-examples
    working_dir: /test-examples
    command: ["python", "run_examples.py"]
    networks:
      - autoformfiller-network
    depends_on:
      - llm-orchestrator

networks:
  autoformfiller-network:
    driver: bridge
