## Traefik Static Configuration

# Konfiguracja globalna
global:
  checkNewVersion: true
  sendAnonymousUsage: false

# Konfiguracja logowania
log:
  level: INFO

# Konfiguracja API
api:
  insecure: true
  dashboard: true

# Konfiguracja dostawców
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
  file:
    filename: /etc/traefik/dynamic_conf.yml
    watch: true

# Konfiguracja punktów wejścia
entryPoints:
  web:
    address: ":80"
  dashboard:
    address: ":8080"
