version: '3.8'

services:
  # API Gateway (Traefik)
  api-gateway:
    build: ./microservices/api-gateway
    container_name: llm-api-gateway
    ports:
      - "80:80"      # API
      - "8080:8080"  # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - llm-network
    depends_on:
      - model-service
    restart: unless-stopped

  # Model Service
  model-service:
    build: 
      context: ./microservices/model-service
      dockerfile: Dockerfile
    container_name: llm-model-service
    environment:
      - MODEL_PATH=/app/models/tinyllama
      - USE_INT8=true
      - MODEL_SERVICE_PORT=5000
    volumes:
      - ./models:/app/models
      - ./.cache/pip:/root/.cache/pip
      - ./.cache/models:/app/.cache/models
    networks:
      - llm-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G

networks:
  llm-network:
    driver: bridge
